[package]
name = "x32_set_preset"
version = "0.1.0"
edition = "2021"

[lib]
name = "x32_set_preset"
path = "src/lib.rs"

[[bin]]
name = "x32_set_preset"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
x32_lib = { workspace = true }
osc_lib = { workspace = true }
tokio = { workspace = true }
