
use std::fmt;

/// Represents the type of an OSC command.
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum CommandType {
    /// No type.
    Nil,
    I32,
    F32,
    S32,
    B32,
    E32,
    P32,
    Res2,
    Res3,
    Res4,
    Fx32,
    OffOn,
    CMono,
    CSolo,
    CTalk,
    CTalkAB,
    COsc,
    CRoutSw,
    CRoutIn,
    CRoutAc,
    CRoutOt,
    CRoutPlay,
    CCtrl,
    CEnc,
    CTape,
    CMix,
    ChCo,
    ChDe,
    ChPr,
    ChGa,
    ChGf,
    ChDy,
    ChDf,
    ChIn,
    ChEq,
    ChMx,
    ChMo,
    ChMe,
    ChGrp,
    ChAMix,
    AxPr,
    BsCo,
    MxPr,
    MxDy,
    MsMx,
    FxTyp1,
    FxSrc,
    FxPar1,
    FxTyp2,
    FxPar2,
    OMain,
    OMain2,
    OP16,
    OMainD,
    HAmp,
    Prefs,
    PIR,
    PIQ,
    PCard,
    PRtA,
    PIP,
    PAddr,
    PMask,
    PGway,
    Stat,
    SScreen,
    SCha,
    SMet,
    SRou,
    SSet,
    SLib,
    SFx,
    SMon,
    SUsb,
    SSce,
    SAss,
    SSoloSw,
    SAes,
    STape,
    SOsc,
    STalk,
    Usb,
    SNam,
    SCue,
    SScn,
    SSnp,
    HA,
    Action,
    URec,
    SLibs,
    D48,
    D48A,
    D48G,
    URouO,
    URouI,
    PKey,
}

/// Represents the value of a command.
#[derive(Debug, PartialEq, Clone)]
pub enum CommandValue {
    /// An integer value.
    Int(i32),
    /// A float value.
    Float(f32),
    /// A string value.
    String(&'static str),
    /// A blob of data.
    Data(&'static [u8]),
}

impl fmt::Display for CommandValue {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            CommandValue::Int(i) => write!(f, "{}", i),
            CommandValue::Float(fl) => write!(f, "{}", fl),
            CommandValue::String(s) => write!(f, "{}", s),
            CommandValue::Data(d) => write!(f, "{:?}", d),
        }
    }
}

/// Represents the format of a command.
#[derive(Debug, PartialEq, Clone)]
pub enum Format {
    /// A command type.
    Type(CommandType),
    /// A string format.
    String(String),
}

/// Represents a single OSC command.
pub struct Command {
    /// The OSC command path.
    pub command: &'static str,
    /// The format of the command.
    pub format: Format,
    /// The flags for the command.
    pub flags: i32,
    /// The value of the command.
    pub value: CommandValue,
    /// An optional node associated with the command.
    pub node: Option<&'static [&'static str]>,
}

// Flags
pub const F_GET: i32 = 0x0001;
pub const F_SET: i32 = 0x0002;
pub const F_XET: i32 = F_GET | F_SET;
pub const F_NPR: i32 = 0x0004;
pub const F_FND: i32 = 0x0008;

// Node arrays
pub const OFF_ON: &[&str] = &[" OFF", " ON", ""];
pub const X_MN_MODE: &[&str] = &[" LR+M", " LCR", ""];
pub const X_S_SOURC: &[&str] = &[" OFF", " LR", " LR+C", " LRPFL", " LRAFL", " AUX56", " AUX78", ""];
pub const X_CH_MODE: &[&str] = &[" PFL", " AFL", ""];
pub const X_T_SOURC: &[&str] = &[" INT", " EXT", ""];
pub const X_OSC_SEL: &[&str] = &[" F1", " F2", ""];
pub const X_OSC_TYP: &[&str] = &[" SINE", " PINK", " WHITE", ""];
pub const X_CF_RSW: &[&str] = &[" REC", " PLAY", ""];
pub const X_RTG_IN: &[&str] = &[" AN1-8", " AN9-16", " AN17-24", " AN25-32", " A1-8", " A9-16", " A17-24", " A25-32", " A33-40", " A41-48", " B1-8", " B9-16", " B17-24",	" B25-32", " B33-40", " B41-48", " CARD1-8", " CARD9-16", " CARD17-24", " CARD25-32", ""];
pub const X_RTA_EA: &[&str] = &[" AN1-8", " AN9-16", "AN17-24", " AN25-32", " A1-8",	" A9-16", " A17-24", " A25-32", " A33-40", " A41-48", " B1-8", " B9-16", " B17-24",	" B25-32", " B33-40", " B41-48", " CARD1-8", " CARD9-16", " CARD17-24", " CARD25-32", " OUT1-8", " OUT9-16", " P161-8", " P169-16", " AUX1-6/Mon", " AuxIN1-6/TB", ""];
pub const X_RTI_NA: &[&str] = &[" AUX1-4", " AN1-2", " AN1-4", " AN1-6", " A1-2", " A1-4", " A1-6", " B1-2", " B1-4", " B1-6", " CARD1-2", " CARD1-4", " CARD1-6", ""];
pub const X_ROUT1: &[&str] = &[" AN1-4", " AN9-12", " AN17-20", " AN25-28", " A1-4", " A9-12", " A17-20", " A25-28", " A33-36", " A41-44" ," B1-4", " B9-12", " B17-20", " B25-28", " B33-36", " B41-44", " CARD1-4", " CARD9-12", " CARD17-20", " CARD25-28", " OUT1-4", " OUT9-12", " P161-4", " P169-12", " AUX/CR", " AUX/TB", ""];
pub const X_ROUT5: &[&str] = &[" AN5-8", " AN13-16", " AN21-24", " AN29-32", " A5-8", " A13-16", " A21-24", " A29-32", " A37-40", " A45-48" ," B5-8", " B13-16", " B21-24", " B29-32", " B37-40", " B45-48", " CARD5-8", " CARD13-16", " CARD21-24", " CARD29-32", " OUT5-8", " OUT13-16", " P165-8", " P1613-16", " AUX/CR", " AUX/TB", ""];
pub const X_COLORS: &[&str] = &[" OFF", " RD", " GN", " YE", " BL", " MG", " CY", " WH", " OFFi", " RDi", " GNi", " YEi", " BLi", " MGi", " CYi", " WHi", ""];
pub const X_DY_MODE: &[&str] = &[" COMP", " EXP", ""];
pub const X_DY_DET: &[&str] = &[" PEAK", " RMS", ""];
pub const X_DY_ENV: &[&str] = &[" LIN", " LOG", ""];
pub const X_DY_RAT: &[&str] = &[" 1.1", " 1.3", " 1.5", " 2.0", " 2.5", " 3.0", " 4.0", " 5.0", " 7.0", " 10", " 20", " 100", ""];
pub const X_DYP_POS: &[&str] = &[" PRE", " POST", ""];
pub const X_DYF_TYP: &[&str] = &[" LC6", " LC12", " HC6", " HC12", " 1.0", " 2.0", " 3.0", " 5.0", " 10.0", ""];
pub const X_I_SEL: &[&str] = &[" OFF", " FX1L", " FX1R", " FX2L", " FX2R", " FX3L", " FX3R", " FX4L", " FX4R", " FX5L", " FX5R", " FX6L", " FX6R", " FX7L", " FX7R", " FX8L", " FX8R", " AUX1", " AUX2", " AUX3", " AUX4", " AUX5", " AUX6", ""];
pub const X_EQ_TY2: &[&str] = &[" LCut", " LShv", " PEQ", " VEQ", " HShv", " HCut", " BU6", " BU12", " BS12", " LR12", " BU18", " BU24", " BS24", " LR24", ""];
pub const X_M_TYPE: &[&str] = &[" IN/LC", " <-EQ", " EQ->", " PRE", " POST", " GRP", ""];

pub const XCONFIG: &[Command] = &[
    Command { command: "/config", format: Format::Type(CommandType::OffOn), flags: F_FND, value: CommandValue::Int(16), node: None },
    Command { command: "/config/chlink", format: Format::Type(CommandType::OffOn), flags: F_FND, value: CommandValue::Int(16), node: None },
    Command { command: "/config/chlink/1-2", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/3-4", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/5-6", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/7-8", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/9-10", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/11-12", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/13-14", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/15-16", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/17-18", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/19-20", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/21-22", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/23-24", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/25-26", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/27-28", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/29-30", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/chlink/31-32", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/auxlink", format: Format::Type(CommandType::OffOn), flags: F_FND, value: CommandValue::Int(4), node: None },
    Command { command: "/config/auxlink/1-2", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/auxlink/3-4", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/auxlink/5-6", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/auxlink/7-8", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/fxlink", format: Format::Type(CommandType::OffOn), flags: F_FND, value: CommandValue::Int(4), node: None },
    Command { command: "/config/fxlink/1-2", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/fxlink/3-4", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/fxlink/5-6", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/fxlink/7-8", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/buslink", format: Format::Type(CommandType::OffOn), flags: F_FND, value: CommandValue::Int(8), node: None },
    Command { command: "/config/buslink/1-2", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/buslink/3-4", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/buslink/5-6", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/buslink/7-8", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/buslink/9-10", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/buslink/11-12", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/buslink/13-14", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/buslink/15-16", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/mtxlink", format: Format::Type(CommandType::OffOn), flags: F_FND, value: CommandValue::Int(3), node: None },
    Command { command: "/config/mtxlink/1-2", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/mtxlink/3-4", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/mtxlink/5-6", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/mute", format: Format::Type(CommandType::OffOn), flags: F_FND, value: CommandValue::Int(6), node: None },
    Command { command: "/config/mute/1", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/mute/2", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/mute/3", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/mute/4", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/mute/5", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/mute/6", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/linkcfg", format: Format::Type(CommandType::OffOn), flags: F_FND, value: CommandValue::Int(4), node: None },
    Command { command: "/config/linkcfg/hadly", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/linkcfg/eq", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/linkcfg/dyn", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/linkcfg/fdrmute", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/mono", format: Format::Type(CommandType::CMono), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/mono/mode", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_MN_MODE) },
    Command { command: "/config/mono/link", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/solo", format: Format::Type(CommandType::CSolo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/solo/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/solo/source", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_S_SOURC) },
    Command { command: "/config/solo/sourcetrim", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/solo/chmode", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_CH_MODE) },
    Command { command: "/config/solo/busmode", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_CH_MODE) },
    Command { command: "/config/solo/dcamode", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_CH_MODE) },
    Command { command: "/config/solo/exclusive", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/solo/followsel", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/solo/followsolo", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/solo/dimatt", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/solo/dim", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/solo/mono", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/solo/delay", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/solo/delaytime", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/solo/masterctrl", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/solo/mute", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/solo/dimpfl", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/talk", format: Format::Type(CommandType::CTalk), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/talk/enable", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/talk/source", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_T_SOURC) },
    Command { command: "/config/talk/A", format: Format::Type(CommandType::CTalkAB), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/talk/A/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/talk/A/dim", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/talk/A/latch", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/talk/A/destmap", format: Format::Type(CommandType::P32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/talk/B", format: Format::Type(CommandType::CTalkAB), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/talk/B/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/talk/B/dim", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/talk/B/latch", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/talk/B/destmap", format: Format::Type(CommandType::P32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/osc", format: Format::Type(CommandType::COsc), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/osc/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/osc/f1", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/osc/f2", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/osc/fsel", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_OSC_SEL) },
    Command { command: "/config/osc/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_OSC_TYP) },
    Command { command: "/config/osc/dest", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout", format: Format::Type(CommandType::URouO), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out", format: Format::Type(CommandType::URouO), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/01", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/02", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/03", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/04", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/05", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/06", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/07", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/08", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/09", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/10", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/11", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/12", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/13", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/14", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/15", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/16", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/17", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/18", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/19", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/20", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/21", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/22", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/23", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/24", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/25", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/26", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/27", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/28", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/29", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/30", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/31", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/32", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/33", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/34", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/35", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/36", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/37", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/38", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/39", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/40", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/41", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/42", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/43", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/44", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/45", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/46", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/47", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/out/48", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in", format: Format::Type(CommandType::URouI), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/01", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/02", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/03", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/04", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/05", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/06", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/07", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/08", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/09", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/10", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/11", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/12", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/13", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/14", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/15", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/16", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/17", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/18", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/19", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/20", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/21", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/22", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/23", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/24", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/25", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/26", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/27", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/28", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/29", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/30", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/31", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userrout/in/32", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/routing", format: Format::Type(CommandType::CRoutSw), flags: F_FND, value: CommandValue::Int(1), node: None },
    Command { command: "/config/routing/routswitch", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_CF_RSW) },
    Command { command: "/config/routing/IN", format: Format::Type(CommandType::CRoutIn), flags: F_FND, value: CommandValue::Int(5), node: None },
    Command { command: "/config/routing/IN/1-8", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTG_IN) },
    Command { command: "/config/routing/IN/9-16", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTG_IN) },
    Command { command: "/config/routing/IN/17-24", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTG_IN) },
    Command { command: "/config/routing/IN/25-32", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTG_IN) },
    Command { command: "/config/routing/IN/AUX", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTI_NA) },
    Command { command: "/config/routing/AES50A", format: Format::Type(CommandType::CRoutAc), flags: F_FND, value: CommandValue::Int(6), node: None },
    Command { command: "/config/routing/AES50A/1-8", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50A/9-16", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50A/17-24", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50A/25-32", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50A/33-40", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50A/41-48", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50B", format: Format::Type(CommandType::CRoutAc), flags: F_FND, value: CommandValue::Int(6), node: None },
    Command { command: "/config/routing/AES50B/1-8", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50B/9-16", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50B/17-24", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50B/25-32", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50B/33-40", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/AES50B/41-48", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/CARD", format: Format::Type(CommandType::CRoutAc), flags: F_FND, value: CommandValue::Int(4), node: None },
    Command { command: "/config/routing/CARD/1-8", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/CARD/9-16", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/CARD/17-24", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/CARD/25-32", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTA_EA) },
    Command { command: "/config/routing/OUT", format: Format::Type(CommandType::CRoutOt), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/routing/OUT/1-4", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_ROUT1) },
    Command { command: "/config/routing/OUT/9-12", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_ROUT1) },
    Command { command: "/config/routing/OUT/5-8", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_ROUT5) },
    Command { command: "/config/routing/OUT/13-16", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_ROUT5) },
    Command { command: "/config/routing/PLAY", format: Format::Type(CommandType::CRoutIn), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/routing/PLAY/1-8", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTG_IN) },
    Command { command: "/config/routing/PLAY/9-16", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTG_IN) },
    Command { command: "/config/routing/PLAY/17-24", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTG_IN) },
    Command { command: "/config/routing/PLAY/25-32", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTG_IN) },
    Command { command: "/config/routing/PLAY/AUX", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_RTI_NA) },
    Command { command: "/config/userctrl/A", format: Format::Type(CommandType::CCtrl), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userctrl/A/color", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_COLORS) },
    Command { command: "/config/userctrl/A/enc", format: Format::Type(CommandType::CEnc), flags: F_FND, value: CommandValue::Int(4), node: None },
    Command { command: "/config/userctrl/A/enc/1", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/enc/2", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/enc/3", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/enc/4", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/btn", format: Format::Type(CommandType::CEnc), flags: F_FND, value: CommandValue::Int(8), node: None },
    Command { command: "/config/userctrl/A/btn/5", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/btn/6", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/btn/7", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/btn/8", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/btn/9", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/btn/10", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/btn/11", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/A/btn/12", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B", format: Format::Type(CommandType::CCtrl), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userctrl/B/color", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_COLORS) },
    Command { command: "/config/userctrl/B/enc", format: Format::Type(CommandType::CEnc), flags: F_FND, value: CommandValue::Int(4), node: None },
    Command { command: "/config/userctrl/B/enc/1", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/enc/2", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/enc/3", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/enc/4", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/btn", format: Format::Type(CommandType::CEnc), flags: F_FND, value: CommandValue::Int(8), node: None },
    Command { command: "/config/userctrl/B/btn/5", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/btn/6", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/btn/7", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/btn/8", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/btn/9", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/btn/10", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/btn/11", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/B/btn/12", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C", format: Format::Type(CommandType::CCtrl), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/userctrl/C/color", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_COLORS) },
    Command { command: "/config/userctrl/C/enc", format: Format::Type(CommandType::CEnc), flags: F_FND, value: CommandValue::Int(4), node: None },
    Command { command: "/config/userctrl/C/enc/1", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/enc/2", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/enc/3", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/enc/4", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/btn", format: Format::Type(CommandType::CEnc), flags: F_FND, value: CommandValue::Int(8), node: None },
    Command { command: "/config/userctrl/C/btn/5", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/btn/6", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/btn/7", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/btn/8", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/btn/9", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/btn/10", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/btn/11", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/userctrl/C/btn/12", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/tape", format: Format::Type(CommandType::CTape), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/tape/gainL", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/tape/gainR", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/config/tape/autoplay", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/amixenable", format: Format::Type(CommandType::CMix), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/amixenable/X", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/amixenable/Y", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/config/dp48", format: Format::Type(CommandType::D48), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/scope", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/broadcast", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign", format: Format::Type(CommandType::D48A), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/01", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/02", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/03", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/04", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/05", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/06", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/07", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/08", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/09", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/10", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/11", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/12", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/13", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/14", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/15", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/16", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/17", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/18", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/19", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/20", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/21", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/22", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/23", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/24", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/25", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/26", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/27", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/28", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/29", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/30", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/31", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/32", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/33", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/34", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/35", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/36", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/37", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/38", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/39", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/40", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/41", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/42", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/43", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/44", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/45", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/46", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/47", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/assign/48", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/grpname", format: Format::Type(CommandType::D48G), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/config/dp48/grpname/01", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/02", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/03", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/04", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/05", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/06", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/07", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/08", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/09", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/10", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/11", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/config/dp48/grpname/12", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
];

pub const XMAIN: &[Command] = &[
    Command { command: "/main", format: Format::Type(CommandType::BsCo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st", format: Format::Type(CommandType::BsCo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/config", format: Format::Type(CommandType::BsCo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/config/name", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/main/st/config/icon", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/config/color", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_COLORS) },
    Command { command: "/main/st/dyn", format: Format::Type(CommandType::MxDy), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/dyn/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/dyn/mode", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DY_MODE) },
    Command { command: "/main/st/dyn/det", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DY_DET) },
    Command { command: "/main/st/dyn/env", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DY_ENV) },
    Command { command: "/main/st/dyn/thr", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/dyn/ratio", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DY_RAT) },
    Command { command: "/main/st/dyn/knee", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/dyn/mgain", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/dyn/attack", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/dyn/hold", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/dyn/release", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/dyn/pos", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DYP_POS) },
    Command { command: "/main/st/dyn/mix", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/dyn/auto", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/dyn/filter", format: Format::Type(CommandType::ChDf), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/dyn/filter/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/dyn/filter/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DYF_TYP) },
    Command { command: "/main/st/dyn/filter/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/insert", format: Format::Type(CommandType::ChIn), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/insert/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/insert/pos", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DYP_POS) },
    Command { command: "/main/st/insert/sel", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_I_SEL) },
    Command { command: "/main/st/eq", format: Format::Type(CommandType::OffOn), flags: F_FND, value: CommandValue::Int(1), node: None },
    Command { command: "/main/st/eq/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/eq/1", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/eq/1/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/st/eq/1/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/1/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/1/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/2", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/eq/2/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/st/eq/2/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/2/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/2/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/3", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/eq/3/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/st/eq/3/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/3/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/3/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/4", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/eq/4/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/st/eq/4/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/4/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/4/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/5", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/eq/5/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/st/eq/5/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/5/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/5/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/6", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/eq/6/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/st/eq/6/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/6/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/eq/6/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix", format: Format::Type(CommandType::MsMx), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/mix/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/mix/fader", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix/pan", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix/01", format: Format::Type(CommandType::ChMo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/mix/01/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/mix/01/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix/01/pan", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix/01/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_M_TYPE) },
    Command { command: "/main/st/mix/02", format: Format::Type(CommandType::ChMe), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/mix/02/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/mix/02/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix/03", format: Format::Type(CommandType::ChMo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/mix/03/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/mix/03/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix/03/pan", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix/03/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_M_TYPE) },
    Command { command: "/main/st/mix/04", format: Format::Type(CommandType::ChMe), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/mix/04/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/mix/04/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix/05", format: Format::Type(CommandType::ChMo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/mix/05/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/mix/05/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix/05/pan", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/mix/05/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_M_TYPE) },
    Command { command: "/main/st/mix/06", format: Format::Type(CommandType::ChMe), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/mix/06/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/st/mix/06/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/st/grp", format: Format::Type(CommandType::ChGrp), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/grp/dca", format: Format::Type(CommandType::P32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/main/st/grp/mute", format: Format::Type(CommandType::P32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m", format: Format::Type(CommandType::BsCo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/config", format: Format::Type(CommandType::BsCo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/config/name", format: Format::Type(CommandType::S32), flags: F_XET, value: CommandValue::String(""), node: None },
    Command { command: "/main/m/config/icon", format: Format::Type(CommandType::I32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/config/color", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_COLORS) },
    Command { command: "/main/m/dyn", format: Format::Type(CommandType::MxDy), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/dyn/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/dyn/mode", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DY_MODE) },
    Command { command: "/main/m/dyn/det", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DY_DET) },
    Command { command: "/main/m/dyn/env", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DY_ENV) },
    Command { command: "/main/m/dyn/thr", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/dyn/ratio", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DY_RAT) },
    Command { command: "/main/m/dyn/knee", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/dyn/mgain", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/dyn/attack", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/dyn/hold", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/dyn/release", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/dyn/pos", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DYP_POS) },
    Command { command: "/main/m/dyn/mix", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/dyn/auto", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/dyn/filter", format: Format::Type(CommandType::ChDf), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/dyn/filter/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/dyn/filter/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DYF_TYP) },
    Command { command: "/main/m/dyn/filter/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/insert", format: Format::Type(CommandType::ChIn), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/insert/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/insert/pos", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_DYP_POS) },
    Command { command: "/main/m/insert/sel", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_I_SEL) },
    Command { command: "/main/m/eq", format: Format::Type(CommandType::OffOn), flags: F_FND, value: CommandValue::Int(1), node: None },
    Command { command: "/main/m/eq/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/eq/1", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/eq/1/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/m/eq/1/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/1/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/1/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/2", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/eq/2/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/m/eq/2/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/2/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/2/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/3", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/eq/3/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/m/eq/3/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/3/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/3/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/4", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/eq/4/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/m/eq/4/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/4/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/4/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/5", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/eq/5/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/m/eq/5/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/5/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/5/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/6", format: Format::Type(CommandType::ChEq), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/eq/6/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_EQ_TY2) },
    Command { command: "/main/m/eq/6/f", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/6/g", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/eq/6/q", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/mix", format: Format::Type(CommandType::ChMe), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/mix/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/mix/fader", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/mix/01", format: Format::Type(CommandType::ChMo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/mix/01/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/mix/01/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/mix/01/pan", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/mix/01/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_M_TYPE) },
    Command { command: "/main/m/mix/02", format: Format::Type(CommandType::ChMe), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/mix/02/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/mix/02/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/mix/03", format: Format::Type(CommandType::ChMo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/mix/03/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/mix/03/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/mix/03/pan", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/mix/03/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_M_TYPE) },
    Command { command: "/main/m/mix/04", format: Format::Type(CommandType::ChMe), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/mix/04/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/mix/04/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/mix/05", format: Format::Type(CommandType::ChMo), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/mix/05/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/mix/05/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/mix/05/pan", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/mix/05/type", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(X_M_TYPE) },
    Command { command: "/main/m/mix/06", format: Format::Type(CommandType::ChMe), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/mix/06/on", format: Format::Type(CommandType::E32), flags: F_XET, value: CommandValue::Int(0), node: Some(OFF_ON) },
    Command { command: "/main/m/mix/06/level", format: Format::Type(CommandType::F32), flags: F_XET, value: CommandValue::Float(0.0), node: None },
    Command { command: "/main/m/grp", format: Format::Type(CommandType::ChGrp), flags: F_FND, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/grp/dca", format: Format::Type(CommandType::P32), flags: F_XET, value: CommandValue::Int(0), node: None },
    Command { command: "/main/m/grp/mute", format: Format::Type(CommandType::P32), flags: F_XET, value: CommandValue::Int(0), node: None },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_xconfig_length() {
        assert_eq!(XCONFIG.len(), 335);
    }

    #[test]
    fn test_xmain_length() {
        assert_eq!(XMAIN.len(), 182);
    }

    #[test]
    fn test_xconfig_commands() {
        assert_eq!(XCONFIG[2].command, "/config/chlink/1-2");
        assert_eq!(XCONFIG[2].format, Format::Type(CommandType::E32));
        assert_eq!(XCONFIG[2].value, CommandValue::Int(0));
    }

    #[test]
    fn test_xmain_commands() {
        assert_eq!(XMAIN[3].command, "/main/st/config/name");
        assert_eq!(XMAIN[3].format, Format::Type(CommandType::S32));
        assert_eq!(XMAIN[3].value, CommandValue::String(""));
    }
}
